### ISSUE TITLE
实现 tolangc 的词法分析

### ISSUE THREAD

**Issue by wokron** [wokron/tolangc#1]
实现 tolangc 的词法分析模块，从输入流中读取字符并进行分词。需要完成 Token 定义和词法分析流程两部分内容。

该模块应在项目最开始完成开发。

**Comment by hhhesc** [comment]
[词法分析.pdf](https://github.com/wokron/tolangc/files/15213228/default.pdf)

**Comment by hhhesc** [comment]
（Token定义的表写的有点乱，不过应该能看懂

**Comment by wokron** [comment]
> [词法分析.pdf](https://github.com/wokron/tolangc/files/15213228/default.pdf)

:+1: ，不过输入流是否最好为 `istream`？另外这里可以使用引用而不是指针 `run(std::ifstream&)`。

还有，`Lexer` 内部应该不需要存储 Token。Look ahead 部分应当由语法分析部分实现，`Lexer` 只需要一次解析一个 Token 就可以了。或许只需要一个接口 `Next`：

```cpp
bool Next(Token&);
```

其中返回值表示是否有下一个 Token，传入的参数用于返回新解析的 Token。

**Comment by hhhesc** [comment]
[词法分析.pdf](https://github.com/wokron/tolangc/files/15215502/default.pdf)

**Comment by wokron** [comment]
> [词法分析.pdf](https://github.com/wokron/tolangc/files/15215502/default.pdf)

嗯嗯，可以着手开发了

**Comment by hhhesc** [comment]
> > [词法分析.pdf](https://github.com/wokron/tolangc/files/15215502/default.pdf)
> 
> 嗯嗯，可以着手开发了

（我的代码放到lexer分支上了

**Comment by wokron** [comment]
> > > [词法分析.pdf](https://github.com/wokron/tolangc/files/15215502/default.pdf)
> > 
> > 
> > 嗯嗯，可以着手开发了
> 
> （我的代码放到lexer分支上了

创建个 Pull Request
