### ISSUE TITLE
tolangc 中间代码生成：结构缺失

### ISSUE THREAD

**Issue by XingZiiii** [wokron/tolangc#14]
缺少 label 标识实现（没有 LabelTy 相关类别，没有LabelInstruction子类）：
缺少 br 语句实现（BranchInstTy没有被分配，没有BranchInstruction子类）：

相关语法结构：
'tag' Ident ';'
'if' Cond 'to' Ident ';'  | 'to' Ident ';'

**Comment by wokron** [comment]
> 缺少 label 标识实现（没有 LabelTy 相关类别，没有LabelInstruction子类）： 缺少 br 语句实现（BranchInstTy没有被分配，没有BranchInstruction子类）：
> 
> 相关语法结构： 'tag' Ident ';' 'if' Cond 'to' Ident ';' | 'to' Ident ';'

- LLVM 中使用基本块表示一个 Label，因此并没有类似 `LabelInstruction` 的指令。
- 之前确实没有实现 br 语句，不过这周 tony 已经实现了，并且已经合并到了 master 分支。
