### ISSUE TITLE
实现 tolangc 的符号表

### ISSUE THREAD

**Issue by wokron** [wokron/tolangc#4]
实现 tolangc 的符号表。虽然 tolang 十分简单，但应当尽可能考虑符号表的可扩展性，包括对**子程序**的支持以及**类型系统**。

该模块应在项目最开始完成开发。

**Comment by YangYzzzz** [comment]
[Uploading 符号表设计.pdf…]()

**Comment by YangYzzzz** [comment]
[符号表设计.pdf](https://github.com/wokron/tolangc/files/15173079/default.pdf)

**Comment by wokron** [comment]
> [符号表设计.pdf](https://github.com/wokron/tolangc/files/15173079/default.pdf)


:+1:，写得很全面。不过 “类型” 之类的属性是不是用枚举 `enum` 而非数值比较好一些？比如说
```cpp
enum ReturnType {
    FLOAT, // 应为浮点数
    VOID,
};
```
另外 `Symbol` 和 `SymbolTable` 的 `ID` 属性是否有必要？因为指针本身应该就能唯一标识某一符号或符号表了。

**Comment by YangYzzzz** [comment]
已重新修改，测试后提交了

**Comment by wokron** [comment]
- 不要把 ide 配置 `.idea` 和构建目录 `cmake-build-debug` 放到提交中。可以在 `.gitignore` 中忽略。
- 头文件应该放到 `include` 中
- 不要修改 `tests` 下的 `main.cpp` 和 `CMakeLists.txt`
- 将头文件放到 `include` 中，例如 `include/symbol_table.h`，之后使用相对于 `include` 的路径导入，如 `#include "symbol_table.h"` 而不是 `#include "../src/symbol_table/symbol_table.h"`

可以为分支创建一个 Pull Request
