### ISSUE TITLE
定义 tolangc 的中间代码数据结构及其构建接口

### ISSUE THREAD

**Issue by wokron** [wokron/tolangc#5]
定义 tolangc 的中间代码数据结构及其构建接口。由于我们使用 LLVM 作为中间代码形式，应当考虑参考 LLVM 的相关实现。

该模块应在项目最开始完成开发。

**Comment by Lord-Turmoil** [comment]
<https://github.com/Lord-Turmoil/ToMiCompiler/tree/main/tomic/include/tomic/llvm/ir>

我之前的编译器中实现过一个简化的 LLVM，但拙劣地模仿 LLVM 进行了晦涩的封装，并且与输出高度耦合。主要思想还是 `Type` 和 `Value`。

这里考虑基于 tolang 和该方案做进一步简化，省去一些不必要的封装。

**Comment by wokron** [comment]
> https://github.com/Lord-Turmoil/ToMiCompiler/tree/main/tomic/include/tomic/llvm/ir
> 
> 我之前的编译器中实现过一个简化的 LLVM，但拙劣地模仿 LLVM 进行了晦涩的封装，并且与输出高度耦合。主要思想还是 `Type` 和 `Value`。
> 
> 这里考虑基于 tolang 和该方案做进一步简化，省去一些不必要的封装。

可以的。tolang 中的代码只要能提供参考，让同学们将类似的数据结构应用到自己的编译器中就可以了。感觉后续在教程中可以重点讲一下 use-def 链的设计；另外 tolang 只有一种类型，可能还要说明一下 LLVM 的类型系统和实现方法。

**Comment by Lord-Turmoil** [comment]
目前实现了除分支外的部分，以及对应的单元测试。不过将出耦合在了 `Type` 和 `Value` 对应的类中。

**Comment by wokron** [comment]
> 不过将出耦合在了 `Type` 和 `Value` 对应的类中。

这里指的是 “输出” 吗？如果是的话也没太大关系，#7 也会对这一部分再做处理。

**Comment by Lord-Turmoil** [comment]
> 这里指的是 “输出” 吗？如果是的话也没太大关系，#7 也会对这一部分再做处理。

是“输出”，不好意思漏打了一个字。输出没有什么特别的，已经写好了，也在测试里写了。🥲
