### ISSUE TITLE
实现 tolang 的中间代码输出

### ISSUE THREAD

**Issue by wokron** [wokron/tolangc#7]
实现 tolang 的中间代码输出模块。该模块用于将中间代码数据结构输出为文本形式，以便与 LLVM 后端对接。（当然，后续也应当编写 tolangc 自身的后端。）

该模块应在**定义中间代码数据结构**完成后进行开发。

**Comment by XingZiiii** [comment]
中间代码输出看起来已经在 tony--ir-data-structure 分支中完成了，还有其他工作要做吗

**Comment by wokron** [comment]
> 中间代码输出看起来已经在 tony--ir-data-structure 分支中完成了，还有其他工作要做吗

确实。可以考虑实现一下目标代码生成。这个 issue 我就关闭了。
